/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.GridLayout;

/**
 *
 * @author l164251
 */
public class gui_interface extends javax.swing.JFrame {

    /**
     * Creates new form gui_interface
     */
    public gui_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton91.setBackground(new java.awt.Color(102, 102, 255));
        jButton91.setBorder(new javax.swing.border.MatteBorder(null));
        jButton91.setBorderPainted(false);
        jButton91.setIconTextGap(0);
        jButton91.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton91.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton92.setBackground(new java.awt.Color(102, 102, 255));
        jButton92.setBorder(new javax.swing.border.MatteBorder(null));
        jButton92.setBorderPainted(false);
        jButton92.setIconTextGap(0);
        jButton92.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton92.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton93.setBackground(new java.awt.Color(102, 102, 255));
        jButton93.setBorder(new javax.swing.border.MatteBorder(null));
        jButton93.setBorderPainted(false);
        jButton93.setIconTextGap(0);
        jButton93.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton93.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton94.setBackground(new java.awt.Color(102, 102, 255));
        jButton94.setBorder(new javax.swing.border.MatteBorder(null));
        jButton94.setBorderPainted(false);
        jButton94.setIconTextGap(0);
        jButton94.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton94.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton95.setBackground(new java.awt.Color(102, 102, 255));
        jButton95.setBorder(new javax.swing.border.MatteBorder(null));
        jButton95.setBorderPainted(false);
        jButton95.setIconTextGap(0);
        jButton95.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton95.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton96.setBackground(new java.awt.Color(102, 102, 255));
        jButton96.setBorder(new javax.swing.border.MatteBorder(null));
        jButton96.setBorderPainted(false);
        jButton96.setIconTextGap(0);
        jButton96.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton96.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton97.setBackground(new java.awt.Color(255, 255, 255));
        jButton97.setBorder(new javax.swing.border.MatteBorder(null));
        jButton97.setBorderPainted(false);
        jButton97.setIconTextGap(0);
        jButton97.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton97.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton98.setBackground(new java.awt.Color(102, 102, 255));
        jButton98.setBorder(new javax.swing.border.MatteBorder(null));
        jButton98.setBorderPainted(false);
        jButton98.setIconTextGap(0);
        jButton98.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton98.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton99.setBackground(new java.awt.Color(255, 255, 255));
        jButton99.setBorder(new javax.swing.border.MatteBorder(null));
        jButton99.setBorderPainted(false);
        jButton99.setIconTextGap(0);
        jButton99.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton99.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton100.setBackground(new java.awt.Color(102, 102, 255));
        jButton100.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton100.setText("1");
        jButton100.setBorder(new javax.swing.border.MatteBorder(null));
        jButton100.setBorderPainted(false);
        jButton100.setIconTextGap(0);
        jButton100.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton100.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton101.setBackground(new java.awt.Color(255, 255, 255));
        jButton101.setBorder(new javax.swing.border.MatteBorder(null));
        jButton101.setBorderPainted(false);
        jButton101.setIconTextGap(0);
        jButton101.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton101.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton102.setBackground(new java.awt.Color(102, 102, 255));
        jButton102.setBorder(new javax.swing.border.MatteBorder(null));
        jButton102.setBorderPainted(false);
        jButton102.setIconTextGap(0);
        jButton102.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton102.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton103.setBackground(new java.awt.Color(255, 255, 255));
        jButton103.setBorder(new javax.swing.border.MatteBorder(null));
        jButton103.setBorderPainted(false);
        jButton103.setIconTextGap(0);
        jButton103.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton103.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton104.setBackground(new java.awt.Color(255, 255, 255));
        jButton104.setBorder(new javax.swing.border.MatteBorder(null));
        jButton104.setBorderPainted(false);
        jButton104.setIconTextGap(0);
        jButton104.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton104.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton105.setBackground(new java.awt.Color(255, 255, 255));
        jButton105.setBorder(new javax.swing.border.MatteBorder(null));
        jButton105.setBorderPainted(false);
        jButton105.setIconTextGap(0);
        jButton105.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton105.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton106.setBackground(new java.awt.Color(102, 102, 255));
        jButton106.setBorder(new javax.swing.border.MatteBorder(null));
        jButton106.setBorderPainted(false);
        jButton106.setIconTextGap(0);
        jButton106.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton106.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton107.setBackground(new java.awt.Color(102, 102, 255));
        jButton107.setBorder(new javax.swing.border.MatteBorder(null));
        jButton107.setBorderPainted(false);
        jButton107.setIconTextGap(0);
        jButton107.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton107.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton108.setBackground(new java.awt.Color(102, 102, 255));
        jButton108.setBorder(new javax.swing.border.MatteBorder(null));
        jButton108.setBorderPainted(false);
        jButton108.setIconTextGap(0);
        jButton108.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton108.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton109.setBackground(new java.awt.Color(102, 102, 255));
        jButton109.setBorder(new javax.swing.border.MatteBorder(null));
        jButton109.setBorderPainted(false);
        jButton109.setIconTextGap(0);
        jButton109.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton109.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton110.setBackground(new java.awt.Color(102, 102, 255));
        jButton110.setBorder(new javax.swing.border.MatteBorder(null));
        jButton110.setBorderPainted(false);
        jButton110.setIconTextGap(0);
        jButton110.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton110.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton111.setBackground(new java.awt.Color(102, 102, 255));
        jButton111.setBorder(new javax.swing.border.MatteBorder(null));
        jButton111.setBorderPainted(false);
        jButton111.setIconTextGap(0);
        jButton111.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton111.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton112.setBackground(new java.awt.Color(102, 102, 255));
        jButton112.setBorder(new javax.swing.border.MatteBorder(null));
        jButton112.setBorderPainted(false);
        jButton112.setIconTextGap(0);
        jButton112.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton112.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton113.setBackground(new java.awt.Color(102, 102, 255));
        jButton113.setBorder(new javax.swing.border.MatteBorder(null));
        jButton113.setBorderPainted(false);
        jButton113.setIconTextGap(0);
        jButton113.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton113.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton114.setBackground(new java.awt.Color(102, 102, 255));
        jButton114.setBorder(new javax.swing.border.MatteBorder(null));
        jButton114.setBorderPainted(false);
        jButton114.setIconTextGap(0);
        jButton114.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton114.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton115.setBackground(new java.awt.Color(102, 102, 255));
        jButton115.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jButton115.setBorder(new javax.swing.border.MatteBorder(null));
        jButton115.setBorderPainted(false);
        jButton115.setIconTextGap(0);
        jButton115.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton115.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton116.setBackground(new java.awt.Color(102, 102, 255));
        jButton116.setBorder(new javax.swing.border.MatteBorder(null));
        jButton116.setBorderPainted(false);
        jButton116.setIconTextGap(0);
        jButton116.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton116.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton117.setBackground(new java.awt.Color(102, 102, 255));
        jButton117.setBorder(new javax.swing.border.MatteBorder(null));
        jButton117.setBorderPainted(false);
        jButton117.setIconTextGap(0);
        jButton117.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton117.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton118.setBackground(new java.awt.Color(255, 255, 255));
        jButton118.setBorder(new javax.swing.border.MatteBorder(null));
        jButton118.setBorderPainted(false);
        jButton118.setIconTextGap(0);
        jButton118.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton118.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton119.setBackground(new java.awt.Color(102, 102, 255));
        jButton119.setForeground(new java.awt.Color(51, 51, 255));
        jButton119.setBorder(new javax.swing.border.MatteBorder(null));
        jButton119.setBorderPainted(false);
        jButton119.setIconTextGap(0);
        jButton119.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton119.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton120.setBackground(new java.awt.Color(102, 102, 255));
        jButton120.setBorder(new javax.swing.border.MatteBorder(null));
        jButton120.setBorderPainted(false);
        jButton120.setIconTextGap(0);
        jButton120.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton120.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton121.setBackground(new java.awt.Color(102, 102, 255));
        jButton121.setBorder(new javax.swing.border.MatteBorder(null));
        jButton121.setBorderPainted(false);
        jButton121.setIconTextGap(0);
        jButton121.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton121.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton122.setBackground(new java.awt.Color(102, 102, 255));
        jButton122.setBorder(new javax.swing.border.MatteBorder(null));
        jButton122.setBorderPainted(false);
        jButton122.setIconTextGap(0);
        jButton122.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton122.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton123.setBackground(new java.awt.Color(102, 102, 255));
        jButton123.setBorder(new javax.swing.border.MatteBorder(null));
        jButton123.setBorderPainted(false);
        jButton123.setIconTextGap(0);
        jButton123.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton123.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton124.setBackground(new java.awt.Color(102, 102, 255));
        jButton124.setBorder(new javax.swing.border.MatteBorder(null));
        jButton124.setBorderPainted(false);
        jButton124.setIconTextGap(0);
        jButton124.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton124.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton125.setBackground(new java.awt.Color(102, 102, 255));
        jButton125.setBorder(new javax.swing.border.MatteBorder(null));
        jButton125.setBorderPainted(false);
        jButton125.setIconTextGap(0);
        jButton125.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton125.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton126.setBackground(new java.awt.Color(102, 102, 255));
        jButton126.setBorder(new javax.swing.border.MatteBorder(null));
        jButton126.setBorderPainted(false);
        jButton126.setIconTextGap(0);
        jButton126.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton126.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton127.setBackground(new java.awt.Color(102, 102, 255));
        jButton127.setBorder(new javax.swing.border.MatteBorder(null));
        jButton127.setBorderPainted(false);
        jButton127.setIconTextGap(0);
        jButton127.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton127.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton128.setBackground(new java.awt.Color(255, 255, 255));
        jButton128.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton128.setText("1");
        jButton128.setBorder(new javax.swing.border.MatteBorder(null));
        jButton128.setBorderPainted(false);
        jButton128.setIconTextGap(0);
        jButton128.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton128ActionPerformed(evt);
            }
        });

        jButton129.setBackground(new java.awt.Color(102, 102, 255));
        jButton129.setBorder(new javax.swing.border.MatteBorder(null));
        jButton129.setBorderPainted(false);
        jButton129.setIconTextGap(0);
        jButton129.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton129.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton129ActionPerformed(evt);
            }
        });

        jButton130.setBackground(new java.awt.Color(102, 102, 255));
        jButton130.setBorder(new javax.swing.border.MatteBorder(null));
        jButton130.setBorderPainted(false);
        jButton130.setIconTextGap(0);
        jButton130.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton130.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton131.setBackground(new java.awt.Color(255, 255, 255));
        jButton131.setBorder(new javax.swing.border.MatteBorder(null));
        jButton131.setBorderPainted(false);
        jButton131.setIconTextGap(0);
        jButton131.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton131.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton132.setBackground(new java.awt.Color(255, 255, 255));
        jButton132.setBorder(new javax.swing.border.MatteBorder(null));
        jButton132.setBorderPainted(false);
        jButton132.setIconTextGap(0);
        jButton132.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton132.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton133.setBackground(new java.awt.Color(255, 255, 255));
        jButton133.setBorder(new javax.swing.border.MatteBorder(null));
        jButton133.setBorderPainted(false);
        jButton133.setIconTextGap(0);
        jButton133.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton133.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton134.setBackground(new java.awt.Color(102, 102, 255));
        jButton134.setBorder(new javax.swing.border.MatteBorder(null));
        jButton134.setBorderPainted(false);
        jButton134.setIconTextGap(0);
        jButton134.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton134.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton135.setBackground(new java.awt.Color(255, 255, 255));
        jButton135.setBorder(new javax.swing.border.MatteBorder(null));
        jButton135.setBorderPainted(false);
        jButton135.setIconTextGap(0);
        jButton135.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton135.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton136.setBackground(new java.awt.Color(255, 255, 255));
        jButton136.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton136.setText("3");
        jButton136.setBorder(new javax.swing.border.MatteBorder(null));
        jButton136.setBorderPainted(false);
        jButton136.setIconTextGap(0);
        jButton136.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton136.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton136.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton136ActionPerformed(evt);
            }
        });

        jButton137.setBackground(new java.awt.Color(255, 255, 255));
        jButton137.setBorder(new javax.swing.border.MatteBorder(null));
        jButton137.setBorderPainted(false);
        jButton137.setIconTextGap(0);
        jButton137.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton137.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton138.setBackground(new java.awt.Color(102, 102, 255));
        jButton138.setBorder(new javax.swing.border.MatteBorder(null));
        jButton138.setBorderPainted(false);
        jButton138.setIconTextGap(0);
        jButton138.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton138.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton139.setBackground(new java.awt.Color(102, 102, 255));
        jButton139.setBorder(new javax.swing.border.MatteBorder(null));
        jButton139.setBorderPainted(false);
        jButton139.setIconTextGap(0);
        jButton139.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton139.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton140.setBackground(new java.awt.Color(102, 102, 255));
        jButton140.setBorder(new javax.swing.border.MatteBorder(null));
        jButton140.setBorderPainted(false);
        jButton140.setIconTextGap(0);
        jButton140.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton140.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton141.setBackground(new java.awt.Color(255, 255, 255));
        jButton141.setBorder(new javax.swing.border.MatteBorder(null));
        jButton141.setBorderPainted(false);
        jButton141.setIconTextGap(0);
        jButton141.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton141.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton142.setBackground(new java.awt.Color(255, 255, 255));
        jButton142.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton142.setText("2");
        jButton142.setBorder(new javax.swing.border.MatteBorder(null));
        jButton142.setBorderPainted(false);
        jButton142.setIconTextGap(0);
        jButton142.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton142.setPreferredSize(new java.awt.Dimension(0, 0));
        jButton142.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton142ActionPerformed(evt);
            }
        });

        jButton143.setBackground(new java.awt.Color(102, 102, 255));
        jButton143.setBorder(new javax.swing.border.MatteBorder(null));
        jButton143.setBorderPainted(false);
        jButton143.setIconTextGap(0);
        jButton143.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton143.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton144.setBackground(new java.awt.Color(102, 102, 255));
        jButton144.setBorder(new javax.swing.border.MatteBorder(null));
        jButton144.setBorderPainted(false);
        jButton144.setIconTextGap(0);
        jButton144.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton144.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton145.setBackground(new java.awt.Color(255, 255, 255));
        jButton145.setBorder(new javax.swing.border.MatteBorder(null));
        jButton145.setBorderPainted(false);
        jButton145.setIconTextGap(0);
        jButton145.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton145.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton146.setBackground(new java.awt.Color(255, 255, 255));
        jButton146.setBorder(new javax.swing.border.MatteBorder(null));
        jButton146.setBorderPainted(false);
        jButton146.setIconTextGap(0);
        jButton146.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton146.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton147.setBackground(new java.awt.Color(102, 102, 255));
        jButton147.setBorder(new javax.swing.border.MatteBorder(null));
        jButton147.setBorderPainted(false);
        jButton147.setIconTextGap(0);
        jButton147.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton147.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton148.setBackground(new java.awt.Color(255, 255, 255));
        jButton148.setBorder(new javax.swing.border.MatteBorder(null));
        jButton148.setBorderPainted(false);
        jButton148.setIconTextGap(0);
        jButton148.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton148.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton149.setBackground(new java.awt.Color(102, 102, 255));
        jButton149.setBorder(new javax.swing.border.MatteBorder(null));
        jButton149.setBorderPainted(false);
        jButton149.setIconTextGap(0);
        jButton149.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton149.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton150.setBackground(new java.awt.Color(102, 102, 255));
        jButton150.setBorder(new javax.swing.border.MatteBorder(null));
        jButton150.setBorderPainted(false);
        jButton150.setIconTextGap(0);
        jButton150.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton150.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton151.setBackground(new java.awt.Color(102, 102, 255));
        jButton151.setBorder(new javax.swing.border.MatteBorder(null));
        jButton151.setBorderPainted(false);
        jButton151.setIconTextGap(0);
        jButton151.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton151.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton152.setBackground(new java.awt.Color(255, 255, 255));
        jButton152.setBorder(new javax.swing.border.MatteBorder(null));
        jButton152.setBorderPainted(false);
        jButton152.setIconTextGap(0);
        jButton152.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton152.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton153.setBackground(new java.awt.Color(255, 255, 255));
        jButton153.setBorder(new javax.swing.border.MatteBorder(null));
        jButton153.setBorderPainted(false);
        jButton153.setIconTextGap(0);
        jButton153.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton153.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton154.setBackground(new java.awt.Color(102, 102, 255));
        jButton154.setBorder(new javax.swing.border.MatteBorder(null));
        jButton154.setBorderPainted(false);
        jButton154.setIconTextGap(0);
        jButton154.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton154.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton155.setBackground(new java.awt.Color(102, 102, 255));
        jButton155.setBorder(new javax.swing.border.MatteBorder(null));
        jButton155.setBorderPainted(false);
        jButton155.setIconTextGap(0);
        jButton155.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton155.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton156.setBackground(new java.awt.Color(255, 255, 255));
        jButton156.setBorder(new javax.swing.border.MatteBorder(null));
        jButton156.setBorderPainted(false);
        jButton156.setIconTextGap(0);
        jButton156.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton156.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton157.setBackground(new java.awt.Color(255, 255, 255));
        jButton157.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton157.setText("1");
        jButton157.setBorder(new javax.swing.border.MatteBorder(null));
        jButton157.setBorderPainted(false);
        jButton157.setIconTextGap(0);
        jButton157.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton157.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton158.setBackground(new java.awt.Color(255, 255, 255));
        jButton158.setBorder(new javax.swing.border.MatteBorder(null));
        jButton158.setBorderPainted(false);
        jButton158.setIconTextGap(0);
        jButton158.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton158.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton159.setBackground(new java.awt.Color(255, 255, 255));
        jButton159.setBorder(new javax.swing.border.MatteBorder(null));
        jButton159.setBorderPainted(false);
        jButton159.setIconTextGap(0);
        jButton159.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton159.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton160.setBackground(new java.awt.Color(255, 255, 255));
        jButton160.setBorder(new javax.swing.border.MatteBorder(null));
        jButton160.setBorderPainted(false);
        jButton160.setIconTextGap(0);
        jButton160.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton160.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton161.setBackground(new java.awt.Color(102, 102, 255));
        jButton161.setBorder(new javax.swing.border.MatteBorder(null));
        jButton161.setBorderPainted(false);
        jButton161.setIconTextGap(0);
        jButton161.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton161.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton162.setBackground(new java.awt.Color(102, 102, 255));
        jButton162.setBorder(new javax.swing.border.MatteBorder(null));
        jButton162.setBorderPainted(false);
        jButton162.setIconTextGap(0);
        jButton162.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton162.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton163.setBackground(new java.awt.Color(102, 102, 255));
        jButton163.setBorder(new javax.swing.border.MatteBorder(null));
        jButton163.setBorderPainted(false);
        jButton163.setIconTextGap(0);
        jButton163.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton163.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton164.setBackground(new java.awt.Color(255, 255, 255));
        jButton164.setBorder(new javax.swing.border.MatteBorder(null));
        jButton164.setBorderPainted(false);
        jButton164.setIconTextGap(0);
        jButton164.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton164.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton165.setBackground(new java.awt.Color(102, 102, 255));
        jButton165.setBorder(new javax.swing.border.MatteBorder(null));
        jButton165.setBorderPainted(false);
        jButton165.setIconTextGap(0);
        jButton165.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton165.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton166.setBackground(new java.awt.Color(255, 255, 255));
        jButton166.setBorder(new javax.swing.border.MatteBorder(null));
        jButton166.setBorderPainted(false);
        jButton166.setIconTextGap(0);
        jButton166.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton166.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton167.setBackground(new java.awt.Color(255, 255, 255));
        jButton167.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton167.setText("1");
        jButton167.setBorder(new javax.swing.border.MatteBorder(null));
        jButton167.setBorderPainted(false);
        jButton167.setIconTextGap(0);
        jButton167.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton167.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton168.setBackground(new java.awt.Color(255, 255, 255));
        jButton168.setBorder(new javax.swing.border.MatteBorder(null));
        jButton168.setBorderPainted(false);
        jButton168.setIconTextGap(0);
        jButton168.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton168.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton169.setBackground(new java.awt.Color(102, 102, 255));
        jButton169.setBorder(new javax.swing.border.MatteBorder(null));
        jButton169.setBorderPainted(false);
        jButton169.setIconTextGap(0);
        jButton169.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton169.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton170.setBackground(new java.awt.Color(255, 255, 255));
        jButton170.setBorder(new javax.swing.border.MatteBorder(null));
        jButton170.setBorderPainted(false);
        jButton170.setIconTextGap(0);
        jButton170.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton170.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton171.setBackground(new java.awt.Color(102, 102, 255));
        jButton171.setBorder(new javax.swing.border.MatteBorder(null));
        jButton171.setBorderPainted(false);
        jButton171.setIconTextGap(0);
        jButton171.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton171.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton172.setBackground(new java.awt.Color(255, 255, 255));
        jButton172.setBorder(new javax.swing.border.MatteBorder(null));
        jButton172.setBorderPainted(false);
        jButton172.setIconTextGap(0);
        jButton172.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton172.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton173.setBackground(new java.awt.Color(102, 102, 255));
        jButton173.setBorder(new javax.swing.border.MatteBorder(null));
        jButton173.setBorderPainted(false);
        jButton173.setIconTextGap(0);
        jButton173.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton173.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton174.setBackground(new java.awt.Color(102, 102, 255));
        jButton174.setBorder(new javax.swing.border.MatteBorder(null));
        jButton174.setBorderPainted(false);
        jButton174.setIconTextGap(0);
        jButton174.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton174.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton175.setBackground(new java.awt.Color(102, 102, 255));
        jButton175.setBorder(new javax.swing.border.MatteBorder(null));
        jButton175.setBorderPainted(false);
        jButton175.setIconTextGap(0);
        jButton175.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton175.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton176.setBackground(new java.awt.Color(102, 102, 255));
        jButton176.setBorder(new javax.swing.border.MatteBorder(null));
        jButton176.setBorderPainted(false);
        jButton176.setIconTextGap(0);
        jButton176.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton176.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton177.setBackground(new java.awt.Color(255, 255, 255));
        jButton177.setBorder(new javax.swing.border.MatteBorder(null));
        jButton177.setBorderPainted(false);
        jButton177.setIconTextGap(0);
        jButton177.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton177.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton178.setBackground(new java.awt.Color(255, 255, 255));
        jButton178.setBorder(new javax.swing.border.MatteBorder(null));
        jButton178.setBorderPainted(false);
        jButton178.setIconTextGap(0);
        jButton178.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton178.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton179.setBackground(new java.awt.Color(255, 255, 255));
        jButton179.setBorder(new javax.swing.border.MatteBorder(null));
        jButton179.setBorderPainted(false);
        jButton179.setIconTextGap(0);
        jButton179.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton179.setPreferredSize(new java.awt.Dimension(0, 0));

        jButton180.setBackground(new java.awt.Color(255, 255, 255));
        jButton180.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton180.setText("1");
        jButton180.setBorder(new javax.swing.border.MatteBorder(null));
        jButton180.setBorderPainted(false);
        jButton180.setIconTextGap(0);
        jButton180.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton180.setPreferredSize(new java.awt.Dimension(0, 0));

        jTextField1.setText("Score : ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Time: ");

        jTextField3.setText("0");

        jTextField4.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton122, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton107, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton109, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton112, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton113, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton114, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(190, 190, 190)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton128, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(405, 405, 405))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton127, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton126, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton125, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton124, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton123, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton115, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(438, 438, 438))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton139, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton169, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton105, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton179, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton159, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton149, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton173, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton108, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton91, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton161, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton151, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton141, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton175, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton110, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton92, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton162, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton152, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton142, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton93, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton163, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton170, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton153, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton143, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton94, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton164, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton172, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton154, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton144, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton95, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton165, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton174, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton155, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton145, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton96, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton166, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton102, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton176, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton156, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton146, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton97, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton167, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton103, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton177, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton157, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton147, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton98, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton168, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton104, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton178, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton158, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton148, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton171, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton180, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton160, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton150, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton140, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(405, 405, 405)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton129, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton131, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton132, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton133, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton134, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton135, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton136, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton137, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton138, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton130, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(405, 405, 405)))))
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton114, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton113, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton112, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton109, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton107, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton122, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton115, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton123, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton124, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton125, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton126, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton127, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton128, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton138, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton137, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton136, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton135, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton134, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton133, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton132, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton131, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton129, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton130, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton148, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton147, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton146, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton145, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton144, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton143, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton142, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton141, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton139, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton140, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton158, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton157, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton156, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton155, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton154, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton153, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton152, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton151, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton149, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton150, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton178, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton177, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton176, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton174, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton172, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton170, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton162, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton161, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton159, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton160, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton104, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton103, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton102, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton92, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton91, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton179, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton180, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton168, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton167, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton166, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton165, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton164, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton163, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton110, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton108, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton105, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton98, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton97, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton96, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton95, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton94, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton93, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton175, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton173, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton169, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton171, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton128ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton128ActionPerformed

    private void jButton142ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton142ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton142ActionPerformed

    private void jButton129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton129ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton129ActionPerformed

    private void jButton136ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton136ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton136ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_interface().setVisible(true);
            }
        });
    }
 //   GridLayout experimentLayout = new GridLayout(5,5);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
